[package]
name = "shared_rust_services"
version = "0.1.0"
edition = "2024"

[lib]
name = "services"
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
chrono-tz = "0.10"
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py310"] }
numpy = "0.23"
libm = "0.2"
uuid = { version = "1", features = ["v4"] }
