"""Authoritative constants for Active Options runtime thresholds."""

ACTIVE_OPTIONS_DEFAULT_LIMIT = 5

ACTIVE_OPTIONS_CHARM_SURGE_START_HOUR_ET = 14
ACTIVE_OPTIONS_CHARM_SURGE_END_HOUR_ET = 16

ACTIVE_OPTIONS_PLACEHOLDER_SIGNATURE_PREFIX = "__placeholder__#"
ACTIVE_OPTIONS_FLOW_VOLUME_THRESHOLD_MILLION = 1_000_000
ACTIVE_OPTIONS_FLOW_VOLUME_THRESHOLD_THOUSAND = 1_000
ACTIVE_OPTIONS_FLOW_ZSCORE_ROUND_DIGITS = 3
ACTIVE_OPTIONS_SIGNATURE_STRIKE_ROUND_DIGITS = 4

ACTIVE_OPTIONS_FLOW_SIGNAL_STATE_LIVE = "LIVE"
ACTIVE_OPTIONS_FLOW_SIGNAL_STATE_DEGRADED = "DEGRADED"

ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_MISSING_GAMMA = "missing_gamma"
ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_MISSING_VANNA = "missing_vanna"
ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_MISSING_TURNOVER = "missing_turnover"
ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_ALL_ENGINES_INACTIVE = "all_engines_inactive"

__all__ = [
    "ACTIVE_OPTIONS_CHARM_SURGE_END_HOUR_ET",
    "ACTIVE_OPTIONS_CHARM_SURGE_START_HOUR_ET",
    "ACTIVE_OPTIONS_DEFAULT_LIMIT",
    "ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_ALL_ENGINES_INACTIVE",
    "ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_MISSING_GAMMA",
    "ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_MISSING_TURNOVER",
    "ACTIVE_OPTIONS_FLOW_SIGNAL_REASON_MISSING_VANNA",
    "ACTIVE_OPTIONS_FLOW_SIGNAL_STATE_DEGRADED",
    "ACTIVE_OPTIONS_FLOW_SIGNAL_STATE_LIVE",
    "ACTIVE_OPTIONS_FLOW_VOLUME_THRESHOLD_MILLION",
    "ACTIVE_OPTIONS_FLOW_VOLUME_THRESHOLD_THOUSAND",
    "ACTIVE_OPTIONS_FLOW_ZSCORE_ROUND_DIGITS",
    "ACTIVE_OPTIONS_PLACEHOLDER_SIGNATURE_PREFIX",
    "ACTIVE_OPTIONS_SIGNATURE_STRIKE_ROUND_DIGITS",
]
