"""Authoritative constants for Active Options runtime thresholds."""

ACTIVE_OPTIONS_DEFAULT_LIMIT = 5
ACTIVE_OPTIONS_SWITCH_CONFIRM_TICKS = 3

ACTIVE_OPTIONS_CHARM_SURGE_START_HOUR_ET = 14
ACTIVE_OPTIONS_CHARM_SURGE_END_HOUR_ET = 16

ACTIVE_OPTIONS_PLACEHOLDER_SIGNATURE_PREFIX = "__placeholder__#"
ACTIVE_OPTIONS_FLOW_VOLUME_THRESHOLD_MILLION = 1_000_000
ACTIVE_OPTIONS_FLOW_VOLUME_THRESHOLD_THOUSAND = 1_000
ACTIVE_OPTIONS_FLOW_ZSCORE_ROUND_DIGITS = 3
ACTIVE_OPTIONS_SIGNATURE_STRIKE_ROUND_DIGITS = 4
